site_name: Wildlife Tools
repo_url: https://github.com/WildlifeDatasets/wildlife-tools
repo_name: wildlife-tools

theme:
  name: "material"
  features:
    - navigation.sections
    - content.code.copy    

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [wildlife_tools]
          options:
            show_source: false
            docstring_style: google
            annotations_path: brief
            members_order: source
            merge_init_into_class: true
            show_root_full_path: true
            show_root_toc_entry: true

nav:
  - Introduction: index.md  
  - Inference: inference.md
  - Training ML models: training.md
  - Pre-trained models:
    - MegaDescriptor: megadescriptor.md
    - WildFusion: wildfusion.md
  - References:
    - Features: reference_features.md
    - Inference: reference_inference.md
    - Similarity: reference_similarity.md
    - Training: reference_training.md
